# Use the host terminal's ANSI palette, matching Herdr's `terminal` theme.
typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
typeset -g POWERLEVEL9K_DIR_FOREGROUND=15
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=7
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=15

typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=6
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=9
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=8

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=2
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=9

typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=9
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=9
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=0
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=9

typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=9
typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=3
typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=7
